# docker-compose.yml
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: slyshno
      POSTGRES_PASSWORD: slyshno_dev
      POSTGRES_DB: slyshno
    ports:
      - '5435:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
